#!/bin/bash

echo "
Creating base image ..."
cat <<EOF > Dockerfile
FROM ubuntu:16.04

RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" > /etc/apt/sources.list.d/pgdg.list

RUN apt update && apt install --yes \
    python-software-properties \
    software-properties-common \
    postgresql \
    postgresql-client \
    postgresql-contrib

### PostGIS
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable
RUN apt update && apt install --yes postgis

EOF
docker build -t $DOCKER_USER/postgres .

########################################################################
echo "
Creating projects-postgres image ..."
cat <<EOF > Dockerfile
FROM arcta/postgres

USER postgres

RUN     /etc/init.d/postgresql start &&\
    psql -c "CREATE USER $DATAUSER WITH PASSWORD '$POSTGRES_PASS';" &&\
    createdb -O $DATAUSER $DATABASE &&\
    psql -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;" $DATABASE

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.6/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.6/main/postgresql.conf

EXPOSE 5432
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]
CMD ["/usr/lib/postgresql/9.6/bin/postgres", "-D", "/var/lib/postgresql/9.6/main", "-c", "config_file=/etc/postgresql/9.6/main/postgresql.conf"]

EOF
docker build -t projects-postgres .
rm Dockerfile
docker images
