#!/bin/bash

########################################################################
### install apache distributed computing tools: spark & storm
########################################################################

SCALA_V=2.11.8
SPARK_V=2.0.2
HADOOP_V=2.7.0
STORM_V=1.0.2

ZOOKEEPER_V=3.4.9
ZEROMQ_V=4.2.0

########################################################################
cd ~
source .local.cnf

### should be alredy there, just to make sure:
sudo apt-get install libtool autoconf pkg-config
sudo apt-get update
sudo apt-get upgrade

sudo apt-get install maven
sudo apt-get install tree

mkdir apache
mkdir apache/run
mkdir apache/run/spark
mkdir apache/run/storm
mkdir apache/run/zookeeper

########################################################################
### install apache spark
curl -O http://downloads.typesafe.com/scala/$SCALA_V/scala-$SCALA_V.tgz
sudo mkdir /usr/local/src/scala
sudo tar xvf scala-$SCALA_V.tgz -C /usr/local/src/scala/

curl -O http://d3kbcqa49mib13.cloudfront.net/spark-$SPARK_V.tgz
tar xvf spark-$SPARK_V.tgz -C apache/
ln -s $HOME/apache/spark-$SPARK_V $HOME/apache/spark

echo "
### master / slaves ####################################################
MASTER=$NODEIP

SPARK_HOME=$HOME/apache/spark
STORM_HOME=$HOME/apache/storm
ZOOKEEPER_HOME=$HOME/apache/zookeeper
SCALA_HOME=/usr/local/src/scala/scala-$SCALA_V

export PATH=\$SCALA_HOME/bin:\$PATH
export PATH=\$STORM_HOME/bin:\$PATH
export PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH

" >> .local.cnf
source .local.cnf

cd $SPARK_HOME
cd $SPARK_HOME
# Building With Hive and JDBC Support
# See: http://spark.apache.org/docs/latest/building-spark.html
# Maven is the official build tool recommended for packaging Spark, and is the build of reference.
# But SBT is supported for day-to-day development since it can provide much faster iterative compilation.
#./build/mvn -Pyarn -Phadoop-$HADOOP_V -Dhadoop.version=$HADOOP_V -Phive -Phive-thriftserver -DskipTests clean package | tee -a "$HOME/install-spark.log" 2>&1
./build/sbt -Pyarn -Phadoop-$HADOOP_V -Dhadoop.version=$HADOOP_V -Phive -Phive-thriftserver -DskipTests clean package | tee -a "$HOME/install-spark.log" 2>&1

echo "localhost
" > $SPARK_HOME/conf/slaves

for ip in ${CLUSTERIPS[*]}
do
    if [ "$ip" != "$NODEIP" ]; then
        echo "$ip
" >> $SPARK_HOME/conf/slaves
    fi
done

echo "#!/usr/bin/env bash

SPARK_MASTER_WEBUI_PORT=8282
" > $SPARK_HOME/conf/spark-env.sh

#sudo groupadd supergroup
#sudo adduser hdfs -g supergroup

########################################################################
### install dependencies: zookeeper and zeromq
cd ~

git clone git://github.com/jedisct1/libsodium.git
cd libsodium
./autogen.sh 
./configure && make check
sudo make install
sudo ldconfig
cd ~

curl -O http://mirror.reverse.net/pub/apache/zookeeper/zookeeper-$ZOOKEEPER_V/zookeeper-$ZOOKEEPER_V.tar.gz
tar -zxvf zookeeper-$ZOOKEEPER_V.tar.gz
mv zookeeper-$ZOOKEEPER_V apache/zookeeper-$ZOOKEEPER_V
ln -s $HOME/apache/zookeeper-$ZOOKEEPER_V $HOME/apache/zookeeper

echo "
tickTime=2000
initLimit=10
syncLimit=5
dataDir=${HOME}/apache/run/zookeeper
clientPort=2181
autopurge.purgeInterval=24
autopurge.snapRetainCount=5
" > $ZOOKEEPER_HOME/conf/zoo.cfg

curl -O http://download.zeromq.org/zeromq-$ZEROMQ_V.tar.gz
tar -xzf zeromq-$ZEROMQ_V.tar.gz
sudo mv zeromq-$ZEROMQ_V /usr/local/zeromq-$ZEROMQ_V

cd /usr/local/zeromq-$ZEROMQ_V
./configure
make
./autogen.sh
./configure && make check
sudo make install | tee -a "$HOME/install-zeromq.log" 2>&1

########################################################################
### install apache storm
cd ~

curl -O http://mirror.cc.columbia.edu/pub/software/apache/storm/apache-storm-$STORM_V/apache-storm-$STORM_V.tar.gz
tar -zxvf apache-storm-$STORM_V.tar.gz
mv apache-storm-$STORM_V apache/storm-$STORM_V
ln -s $HOME/apache/storm-$STORM_V $HOME/apache/storm

cp $STORM_HOME/conf/storm.yaml $STORM_HOME/conf/storm.yaml.orig
echo "
storm.local.dir: \"$HOME/apache/run/storm\"
nimbus.host: \"$NODEIP\"
ui.port: 8383

supervisor.slots.ports:
    - 6700
    - 6701
    - 6702
    - 6703

storm.zookeeper.servers:
     - \"localhost\"
" > $STORM_HOME/conf/storm.yaml

for ip in ${CLUSTERIPS[*]}
do
    if [ "$ip" != "$NODEIP" ]; then
        echo "
     - \"$ip\"
" >> $STORM_HOME/conf/storm.yaml
    fi
done

echo "
drpc.servers:
     - \"localhost\"
" >> $STORM_HOME/conf/storm.yaml

for ip in ${CLUSTERIPS[*]}
do
    if [ "$ip" != "$NODEIP" ]; then
        echo "
     - \"$ip\"
" >> $STORM_HOME/conf/storm.yaml
    fi
done

cd ~
rm -rf libsodium
rm *.tar.gz
rm *.tgz
