#!/bin/bash

########################################################################
### install GCP SDK: https://cloud.google.com/sdk/docs/#deb
### at least one (may be empty) project should be in your GCP account
########################################################################

# Create an environment variable for the correct distribution:
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
# Add the Cloud SDK distribution URI as a package source:
echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
# Import the Google Cloud public key:
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
# Update and install the Cloud SDK:
sudo apt-get update && sudo apt-get install google-cloud-sdk
# Optionally install any of these additional components:
google-cloud-sdk-app-engine-python
google-cloud-sdk-app-engine-java
google-cloud-sdk-datastore-emulator
google-cloud-sdk-pubsub-emulator
google-cloud-sdk-bigtable-emulator
kubectl

# Run gcloud init to get started:
gcloud init
