#!/bin/bash

########################################################################
### set users and fix permissions
### passwords could be set after installation
########################################################################

OWNER=$'server'

sudo useradd -d /home/$OWNER -m $OWNER
sudo usermod -g sudo $OWNER
sudo usermod -s /bin/bash $OWNER
sudo passwd $OWNER


### User rules for $OWNER ###
echo "$OWNER ALL=(ALL) PASSWD:ALL" | sudo tee /etc/sudoers.d/$OWNER

########################################################################
### remove excess of power from aws-init-user
sudo passwd ubuntu
sudo rm /etc/sudoers.d/90-cloud-init-users
