#!/bin/bash

########################################################################
### install system level dependencies using local configuration
########################################################################
cd ~
. .local.cnf

########################################################################
### start installation: latest stable releases using PPA
sudo apt-get update
sudo apt-get upgrade

### python dev #########################################################
sudo apt-get install python3-pip python3-dev python3-software-properties
sudo apt-get install build-essential python3-all-dev pkg-config pandoc
sudo pip3 install --upgrade virtualenv

### libraries ##########################################################
sudo apt-get install libssl-dev gfortran make gcc gcc-multilib g++
sudo apt-get install libpng-dev libfreetype6-dev libatlas-base-dev libffi-dev
sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
sudo apt-get install curl nmap imagemagick
sudo apt-get install php-cli php-gd

### java ###############################################################
sudo apt-add-repository ppa:webupd8team/java && sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo apt-get install oracle-java8-set-default

### mysql ##############################################################
wget http://dev.mysql.com/get/mysql-apt-config_0.3.2-1ubuntu14.04_all.deb
sudo dpkg -i mysql-apt-config_0.3.2-1ubuntu14.04_all.deb
sudo apt-get update
#echo mysql-server-5.7 mysql-server/root_password password $NODE_MYSQL_ROOT_PASS | sudo debconf-set-selections
#echo mysql-server-5.7 mysql-server/root_password_again password $NODE_MYSQL_ROOT_PASS | sudo debconf-set-selections
sudo apt-get install mysql-server-5.7
sudo apt-get install libmysqlclient-dev
rm mysql-apt-config_0.3.2-1ubuntu14.04_all.deb

### elasticsearch ######################################################
wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
sudo apt-get update
sudo apt-get install elasticsearch
echo "cluster.name: $CLUSTER" | sudo tee -a /etc/elasticsearch/elasticsearch.yml
echo "node.name: $NODE" | sudo tee -a /etc/elasticsearch/elasticsearch.yml
sudo update-rc.d elasticsearch defaults 95 10
sudo service elasticsearch start

### redis ##############################################################
sudo apt-get install redis-server
sudo cp /etc/redis/redis.conf /etc/redis/redis.conf.default
echo "requirepass $NODE_REDIS_PASS" | sudo tee -a /etc/redis/redis.conf
sudo service redis-server restart

### mongodb ############################################################
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb.list
sudo apt-get update
sudo apt-get install -y mongodb-org
sudo mkdir -p /data/db
sudo chown -R mongod:mongod /data

### R ##################################################################
sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/"
sudo gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
sudo gpg -a --export E084DAB9 | sudo apt-key add -
sudo apt-get update
sudo apt-get install r-base r-base-dev

### R-shiny http://www.rstudio.com/products/shiny/download-server/ #####
sudo apt-get install gdebi-core
sudo su - -c "R -e \"install.packages('shiny', repos='http://cran.rstudio.com/')\""
wget http://download3.rstudio.org/ubuntu-12.04/x86_64/shiny-server-1.4.2.786-amd64.deb
sudo gdebi shiny-server-1.4.2.786-amd64.deb
rm shiny-server-1.4.2.786-amd64.deb

### geo ################################################################
sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
sudo apt-get install gdal-bin libgdal-dev

### sage math ##########################################################
#sudo apt-add-repository -y ppa:aims/sagemath && sudo apt-get update
#sudo apt-get install sagemath-upstream-binary

### nodejs #############################################################
curl -sL https://deb.nodesource.com/setup | sudo bash -
echo "deb https://deb.nodesource.com/node_4.x trusty main" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt-get install nodejs

### server #############################################################
sudo add-apt-repository ppa:nginx/stable && sudo apt-get update
sudo apt-get install nginx

### docker #############################################################
sudo apt-get install apt-transport-https ca-certificates
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
sudo apt-get install docker-engine

### git ################################################################
sudo apt-get install git-core -f
git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"

########################################################################
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get autoremove
sudo apt-get autoclean

sudo chown -R $USER:$USER $HOME

echo "Installed:
" > install.log
echo "nodejs $(nodejs --version)" >> install.log 2>&1
echo "npm version $(npm -v)" >> install.log 2>&1
echo $(ogrinfo --version) >> install.log 2>&1
echo $(R CMD config --version) >> install.log 2>&1
mysql --version >> install.log 2>&1
mongo --version >> install.log 2>&1
mongod --version >> install.log 2>&1
curl -XGET 'localhost:9200' >> install.log 2>&1
echo "Running:
$(sudo netstat -tulpn)
" >> install.log 2>&1

echo 'Done: see install.log'
head -45 install.log

########################################################################
### do not override after use
chmod 400 ~/install/config-1
