#!/bin/bash

########################################################################
### restart projects production API
########################################################################
. $HOME/.local.cnf
. $HOME/project/reload api $NODE_API_PORT
