#!/bin/bash

########################################################################
### start projects production API
########################################################################
. $HOME/.local.cnf

sudo tee /etc/nginx/upstream/api <<EOF
    upstream api {
        server 127.0.0.1:$NODE_API_PORT;
EOF

for ip in ${CLUSTERIPS[*]}
do
    if [ "$ip" != "$NODEIP" ]; then
        sudo tee -a /etc/nginx/upstream/api <<EOF
        server $ip:$NODE_API_PORT;
EOF
    fi
done

sudo tee -a /etc/nginx/upstream/api <<EOF
    }
EOF

sudo tee /etc/nginx/location/api <<EOF
        location /api {
            rewrite ^/api/(.*) /\$1 break;
            proxy_pass http://api/;
            include proxy_params;
        }
EOF

pm2 start $HOME/NODE_DOC_ROOT/api/app/app.js --name api
sudo service nginx restart
