#!/bin/bash

########################################################################
### stop projects production API
########################################################################
. $HOME/.local.cnf
. $HOME/project/stop api $NODE_API_PORT
