#!/bin/bash

########################################################################
### start project nodejs app
### parameters: $1 project subdirectory
########################################################################

tee ~/$NODE_DOC_ROOT/$1/app/package.json <<EOF
{
    "name": "${1}",
    "version": "0.0.0",
    "author": {
         "name": "${GIT_USER_NAME}",
         "email": "${GIT_USER_EMAIL}"
    },
    "website":{
         "url": "https://www.${DOMAIN}"
    },
    "repository": {
         "type": "git",
         "url": "${GIT_REPO_URL}/${1}"
    },
    "scripts": {
        "deploy": "gcloud app deploy app.yaml"
    },
    "private": true,
    "dependencies": {
        "@google/cloud-debug": "^0.8.3",
        "@google/cloud-trace": "^0.5.5",

        "express": "^4.14.0",
        "serve-favicon": "*",
        "serve-static": "*",
        "express-session": "*",
        "errorhandler": "*",
        "underscore": "*",
        "compression": "*",
        "body-parser": "*",
        "intel": "*",

        "mysql": "*",
        "mongodb": "*",
        "elasticsearch": "*",
        "redis": "*",
        "connect-redis": "*",
        "express-redis-cache": "*"
    },
    "devDependencies": {
        "nodejs-repo-tools": "git+https://github.com/GoogleCloudPlatform/nodejs-repo-tools.git#21daa823090c43fb667157c8b5b0c3b7f45a8357"
    }
}
EOF

chmod 600 ~/$NODE_DOC_ROOT/$1/app/package.json
