#!/bin/bash

########################################################################
### start project nodejs production app
### parameters: $1 project subdirectory
########################################################################

tee ~/$NODE_DOC_ROOT/$1/app/package.json <<EOF
{
    "name": "${1}",
    "version": "0.0.0",
    "author": {
         "name": "${GIT_USER_NAME}",
         "email": "${GIT_USER_EMAIL}"
    },
    "website":{
         "url": "https://www.${DOMAIN}"
    },
    "repository": {
         "type": "git",
         "url": "${GIT_REPO_URL}/${1}"
    },
    "private": true,
    "dependencies": {
        "express": "^4.13.4",
        "serve-favicon": "*",
        "serve-static": "*",
        "express-session": "*",
        "errorhandler": "*",
        "underscore": "*",
        "compression": "*",
        "body-parser": "*",
        "intel": "*",

        "mysql": "*",
        "mongodb": "*",
        "elasticsearch": "*",
        "redis": "*",
        "connect-redis": "*",
        "express-redis-cache": "*"
    }
}
EOF

chmod 600 ~/$NODE_DOC_ROOT/$1/app/package.json
