#!/bin/bash

########################################################################
### creates nodeJS app config file
### args: $1 project subdir $2 project port
########################################################################

echo "
var config = {
    production: {
        mode: 'production',
        port: ${2},
        domains: '*.${DOMAIN}',

        crypto: {
            alg: '${NODE_CRYPTO_ALG}',
            key: '${NODE_CRYPTO_KEY}'
        },
        cookie: {
            key: '${NODE_COOKIE_KEY}',
            age: $NODE_COOKIE_AGE
        },

        mysql: {
            user: '${NODE_DATAUSER}',
            password: '${NODE_MYSQL_PASS}',
            database: '${NODE_DATABASE}',
            host: '${NODE_MYSQL_HOST}',
            port: ${NODE_MYSQL_PORT}
        },
        mongo: {
            user: '${NODE_DATAUSER}',
            password: '${NODE_MONGO_PASS}',
            host: '${NODE_MONGO_HOST}',
            port: ${NODE_MONGO_PORT}
        },
        elasticsearch: {
             host: '${NODE_ES_HOST}'
        },
        redis: {
            db: 2,
            pass: '${NODE_REDIS_PASS}',
            host: '${NODE_REDIS_HOST}',
            port: ${NODE_REDIS_PORT},
        }
    },

    test: {
        port: 4000,
        domains: 'localhost',

        crypto: {
            alg: '${NODE_CRYPTO_ALG}',
            key: '${NODE_CRYPTO_KEY}'
        },
        cookie: {
            key: '${NODE_COOKIE_KEY}',
            age: $NODE_COOKIE_AGE
        },

        mysql: {
            user: '${NODE_DATAUSER}',
            password: '${NODE_MYSQL_PASS}',
            database: '${NODE_DATABASE}'
        },
        mongo: {
            user: '${NODE_DATAUSER}',
            password: '${NODE_MONGO_PASS}'
        },
        elasticsearch: {
             host: 'localhost:9200'
        },
        redis: {
            pass: '${NODE_REDIS_PASS}'
        }
    }
}

module.exports = function(mode) {
    return config[mode || process.argv[2] || 'production'] || config.production;
}
" > ~/${NODE_DOC_ROOT}/${1}/app/config.js

chmod 600 ~/${NODE_DOC_ROOT}/${1}/app/config.js
