#!/bin/bash

########################################################################
### start project nodejs production app
### parameters: $1 project subdirectory
########################################################################

tee ~/$NODE_DOC_ROOT/$1/app/static/index.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1.0, user-scalable=0" />

  <title>${1}</title>
  <link rel="stylesheet" href="/shared-assets/css/app.css" />
</head>
<body>
  <h1>${1} is online!</h1>
</body>
</html>
EOF

chmod 600 ~/$NODE_DOC_ROOT/$1/app/static/index.html
