#!/bin/bash

########################################################################
### start project nodejs app
### parameters: $1 project subdirectory
########################################################################

tee ~/$NODE_DOC_ROOT/$1/app/package.json <<EOF
{
    "name": "${1}",
    "version": "0.0.0",
    "private": true,
    "author": {
         "name": "${GIT_USER_NAME}",
         "email": "${GIT_USER_EMAIL}"
    },
    "repository": {
         "type": "git",
         "url": "${GIT_REPO_URL}/${1}"
    },
    "website":{
         "url": "https://www.${DOMAIN}"
    },
    "scripts": {
        "start": "node app.js",
        "monitor": "nodemon app.js"
    },
    "dependencies": {
        "app-local": "file:../../lib/app-local",

        "express": "^4.14.0",
        "serve-favicon": "*",
        "serve-static": "*"
    },
    "devDependencies": {

    },
    "engines": {
        "node": ">=4.3.2"
    }
}
EOF

chmod 600 ~/$NODE_DOC_ROOT/$1/app/package.json
