
# Deployment to Google Cloud
# https://cloud.google.com/nodejs/getting-started/tutorial-app
runtime: nodejs
env: flex

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$

