#!/bin/bash

########################################################################
### set up a new project as notebook + rstudio + nodejs environment
### args: $1 progect subdirectory name
########################################################################
. ~/.local.cnf

if grep '^[0-9a-zA-Z_\-]*$' <<<$1 ; then
    if [ -d ~/$NODE_DOC_ROOT/$1 ]; then
        echo 'Directory exists... aborting.'

    else
        mkdir ~/$NODE_DOC_ROOT/$1
        cp ~/project/gitignore ~/$NODE_DOC_ROOT/$1/.gitignore

        ### init notebook ##############################################
        cp ~/project/README.ipynb ~/$NODE_DOC_ROOT/$1/README.ipynb
        sed -i "s/NODE_DOC_ROOT/${NODE_DOC_ROOT}/g" ~/$NODE_DOC_ROOT/$1/README.ipynb
        sed -i "s/PROJECT_LABEL/${1}/g" ~/$NODE_DOC_ROOT/$1/README.ipynb
        sed -i "s/DOMAIN/${DOMAIN}/g" ~/$NODE_DOC_ROOT/$1/README.ipynb

        ### init rstudio ###############################################
        cp ~/project/ui.R ~/$NODE_DOC_ROOT/$1/ui.R
        cp ~/project/server.R ~/$NODE_DOC_ROOT/$1/server.R

        ### init nodejs-express application ########################
        mkdir ~/$NODE_DOC_ROOT/$1/app
        cp ~/project/app.js ~/$NODE_DOC_ROOT/$1/app/app.js

        ((last = NODE_PROJECT_PORT + 0))
        ((next = NODE_PROJECT_PORT + 1))

        . ~/project/app-package-json $1

        ln -s ~/node_modules ~/$NODE_DOC_ROOT/$1/app/node_modules
        mkdir ~/$NODE_DOC_ROOT/$1/app/static

        . ~/project/app-index-html $1

        if [ 'info' != $1 ]; then
            ln -s ~/$NODE_DOC_ROOT/info/app/static/shared-assets ~/$NODE_DOC_ROOT/$1/app/static/shared-assets
        fi
        cp ~/project/favicon.png ~/$NODE_DOC_ROOT/$1/app/static/favicon.png
        mkdir ~/$NODE_DOC_ROOT/$1/app/static/pdf
 
        LABEL=${1^^}
        sed -i "s/NODE_PROJECT_PORT=${last}/NODE_PROJECT_${LABEL//-/_}_PORT=${last}\nNODE_PROJECT_PORT=${next}/1" ~/.local.cnf

        ls -l ~/$NODE_DOC_ROOT/$1

        echo "Project location: ~/${NODE_DOC_ROOT}/${1}"
    fi
else
    echo 'Please use: alphanumeric undescore dash';
fi
