#!/bin/bash

########################################################################
### start project nodejs production app
### parameters: $1 project subdirectory
### start --test for test access on port 4444; production otherwise
########################################################################
. $HOME/.local.cnf

access="allow 192.168.1.0/24; deny all;"
mode="TESTING"

if [ "$1" == "--test" ]; then
    label="$2"

elif [ "$2" == "--test" ]; then
    label="$1"

else
    label="$1"
    access="allow all;"
    mode="PRODUCTION"
fi


port=$(grep -P "(?<!\d)\d{4}\s${label}(?!\d)" ~/.project.cnf | sed -e "s/\t${label}//")
echo $port

if [[ -z "$port" || $port = \#* ]] ; then
    echo "${label} is disabled OR does not exists in .project.cnf"
else
    echo "Starting projects $label app in $mode mode on $port port ..."
    sudo tee /etc/nginx/upstream/$1 <<EOF
    upstream $label {
        server 127.0.0.1:$port;
EOF

    for ip in ${CLUSTERIPS[*]}
    do
        if [ "$ip" != "$NODEIP" ]; then
            sudo tee -a /etc/nginx/upstream/$label <<EOF
        server $ip:$port;
EOF
        fi
    done

    sudo tee -a /etc/nginx/upstream/$label <<EOF
    }
EOF
    if [[ " ${NODE_COMMON[*]} " == *" $label "* ]]; then
        location=""
    else
        location="/${NODE_DOC_ROOT}"
    fi

    if [ 'info' == "$label" ]; then
        sudo tee /etc/nginx/location/info <<EOF
        location / {
            ${access}
            proxy_pass http://info/;
            include proxy_params;
        }

        location /notebook/tree/info/app {
            deny all;
        }
EOF
    else
        sudo tee /etc/nginx/location/$label <<EOF
        location ${location}/${label} {
            ${access}
            rewrite ^${location}/${label}/(.*) /\$1 break;
            proxy_pass http://${label}/;
            include proxy_params;
        }

        location /notebook/tree/${label}/app {
            deny all;
        }
EOF
    fi

    cd $HOME/$NODE_DOC_ROOT/${1}/app/
    pm2 start app.js --name $1
    sudo service nginx restart
    echo "$label up!"
fi
