#!/bin/bash

########################################################################
### start apache-storm cluster !!! dev environment !!!
########################################################################
DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

cd $ZOOKEEPER_HOME
./bin/zkServer.sh start

cd $STORM_HOME
./bin/storm nimbus &
./bin/storm supervisor &
./bin/storm ui &

cd $DID
