#!/bin/bash

########################################################################
### start all projects nodejs production
########################################################################
. $HOME/.local.cnf

LIST=$(ls ~/$NODE_DOC_ROOT)
for label in ${LIST[*]}
do
    if [ -d "$label" ]; then
        if [ -f "${HOME}/${NODE_DOC_ROOT}/${label}/app/start" ]; then
            echo "
            Starting $label ..."
            . ~/$NODE_DOC_ROOT/${label}/app/start
        fi
    fi
done
echo 'Done all'
