#!/bin/bash

########################################################################
### star apache-spark cluster
########################################################################
#ssh $MASTER "(cd $SPARK_HOME;./sbin/start-all.sh)"

DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

cd $SPARK_HOME
./sbin/start-master.sh
./sbin/start-slaves.sh

cd $DIR
