#!/bin/bash

########################################################################
### stop apache-spark cluster
########################################################################
#ssh $MASTER "(cd $SPARK_HOME;./sbin/stop-all.sh)"

DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

cd $SPARK_HOME
./sbin/stop-slaves.sh
./sbin/stop-master.sh

cd $DIR
