#!/bin/bash

########################################################################
### stop project nodejs production app
### parameters: $1 project subdirectory
########################################################################
sudo rm /etc/nginx/upstream/$1
sudo rm /etc/nginx/location/$1

pm2 delete $1
sudo service nginx restart
echo "$1 stopped!"
