#!/bin/bash

########################################################################
### stop apache-storm cluster !!! dev environment !!!
########################################################################
DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

cd $ZOOKEEPER_HOME
./bin/zkServer.sh stop

#sudo pkill -TERM -u $USER -f 'backtype.storm.daemon.worker'
#sudo pkill -TERM -u $USER -f 'backtype.storm.daemon.backtype.storm.daemon.supervisor'
#sudo pkill -TERM -u $USER -f 'backtype.storm.daemon.nimbus'

ps aux | grep -ie storm | awk '{print $2}' | xargs kill -9

cd $DIR
