#!/bin/bash

########################################################################
### start projects notebook web-interface
########################################################################
. $HOME/.local.cnf

sudo tee /etc/nginx/upstream/notebook <<EOF
    upstream notebook {
        server 127.0.0.1:${NODE_NOTEBOOK_PORT};
    }
EOF

sudo tee /etc/nginx/location/notebook <<EOF
        ### !!! IMPORTANT !!! ###
        location /notebook {
            allow 192.168.1.0/24;
            deny all;
            proxy_pass http://notebook;
            # proxy_set_header Origin "";
            include proxy_params;
        }
EOF

sudo service notebook start
sudo service nginx restart
echo 'Done'
