#!/bin/bash

########################################################################
### start all projects nodejs production
########################################################################
. $HOME/.local.cnf

LIST=$(ls ~/$NODE_DOC_ROOT)
for label in ${LIST[*]}
do
    if [ -d "${HOME}/${NODE_DOC_ROOT}/${label}" ]; then
        if [ -d "${HOME}/${NODE_DOC_ROOT}/${label}/app" ]; then
            . $HOME/project/start $label $port
        fi
    fi
done
echo 'Done'
