#!/bin/bash

########################################################################
### stop all projects nodejs production
########################################################################
source $HOME/.local.cnf

LIST=$(ls ~/$NODE_DOC_ROOT)
for label in ${LIST[*]}
do
    if [ -d "${HOME}/${NODE_DOC_ROOT}/$label" ]; then
        if [ -d "${HOME}/${NODE_DOC_ROOT}/${label}/app" ]; then
            sudo rm /etc/nginx/upstream/$label
            sudo rm /etc/nginx/location/$label
        fi
    fi
done
pm2 delete all
sudo service nginx restart
echo 'Done'
